import { data } from "autoprefixer";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";




export default function Home() {


  const [key,setKey] = useState()

 
    if (typeof window !== "undefined") {
      // browser code

      window.addEventListener("keydown", (e) => {
        setKey(e);
      });
    }
  





  return (
    <div className="h-screen  gap-8 bg-lightBlueHover flex items-center justify-center">
      <Head>
        <title>Event Key Codes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="flex  items-center justify-center gap-8">
          <div className="flex flex-col ">
            <p className="mb-2 font-bold">Event Key</p>
            <div className="border border-main h-10 flex items-center justify-center font-bold text-titleText bg-white">
              {key?.key}
            </div>
          </div>
          <div className="flex flex-col">
            <p className="mb-2 font-bold">Event Key Code</p>
            <div className="border border-main h-10 text-center flex items-center justify-center font-bold text-titleText bg-white">
              {key?.keyCode}
            </div>
          </div>
          <div className="flex flex-col">
            <p className="mb-2 font-bold">Event Code</p>
            <div className="border border-main h-10 flex items-center justify-center font-bold text-titleText bg-white">
              {key?.code}
            </div>
          </div>
        </div>
        <div className="mt-5 flex items-center justify-center">
          <div className="border border-main py-4 px-5 bg-yellow-500 text-black font-semibold">
            Press any key to get the keyCode
          </div>
        </div>
      </div>
    </div>
  );
}
